version: '3.9'

services:
  proxysql:
    image: proxysql/proxysql:latest
    container_name: proxysql
    ports:
      - "6033:6033"  # client port
      - "6032:6032"  # admin interface
    depends_on:
      - primary
      - replica-1
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf:ro
      - proxysql_data:/var/lib/proxysql
    command: ["proxysql", "--initial", "-f", "-c", "/etc/proxysql.cnf"]
    networks:
      - replication_example

  primary:
   image: dolthub/dolt-sql-server:latest
   container_name: primary
   ports:
     - "3307:3306"  # exposes primary on localhost:3307
   volumes:
     - /abs/path/to/.dolt/creds:/root/.dolt/creds # replace with the real path to your local $HOME/.dolt/creds
     - dolt_primary_data:/var/lib/dolt
     - dolt_primary_dolt_config:/etc/dolt/doltcfg.d
     - dolt_primary_server_config:/etc/dolt/servercfg.d
     - ./primary-init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
   command: [
     "-l", "debug",
   ]
   environment:
     DOLT_CREDS_PUBLIC_KEY: ${DOLT_CREDS_PUBLIC_KEY}
   networks:
     - replication_example

  replica-1:
   image: dolthub/dolt-sql-server:latest
   depends_on:
     - primary
   container_name: replica-1
   ports:
     - "3308:3306"  # exposes primary on localhost:3308
   volumes:
     - /Users/dustin/.dolt/creds:/root/.dolt/creds
     - dolt_replica_1_data:/var/lib/dolt
     - dolt_replica_1_dolt_config:/etc/dolt/doltcfg.d
     - dolt_replica_1_server_config:/etc/dolt/servercfg.d
     - ./replica-1-init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
   command: [
     "-l", "debug",
   ]
   environment:
     DOLT_CREDS_PUBLIC_KEY: ${DOLT_CREDS_PUBLIC_KEY}
   networks:
     - replication_example

networks:
  replication_example:
    driver: bridge

volumes:
  proxysql_data:

  dolt_primary_data:
  dolt_primary_dolt_config:
  dolt_primary_server_config:

  dolt_replica_1_data:
  dolt_replica_1_dolt_config:
  dolt_replica_1_server_config:


